[[redirects]]
  from = "/mp3"
  to = "https://l.chickenfm.com/mobilemp3"
  status = 302
  force = true

[[redirects]]
  from = "/eurovision"
  to = "http://l.chickenfm.com/esc"
  status = 302
  force = true

[[redirects]]
  from = "/esc"
  to = "http://l.chickenfm.com/esc"
  status = 302
  force = true