[[redirects]]
  from = "/mp3"
  to = "https://radio.chickenfm.com/radio/8000/radio.mp3"
  status = 301
  force = true

[[redirects]]
  from = "/eurovision"
  to = "https://radio.chickenfm.com/radio/8030/radio.mp3"
  status = 301
  force = true

[[redirects]]
  from = "/esc"
  to = "https://radio.chickenfm.com/radio/8030/radio.mp3"
  status = 301
  force = true